# Generated by Django 5.1.15 on 2026-05-05 16:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('original_filename', models.CharField(max_length=500)),
                ('doc_type', models.CharField(choices=[('unknown', 'Unknown'), ('contract', 'Contract'), ('nda', 'NDA'), ('court_filing', 'Court filing'), ('general_legal', 'General legal')], default='unknown', max_length=32)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=32)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ldip_documents_mirror',
                'ordering': ('-created_at',),
            },
        ),
    ]
