"""Prometheus metrics for the ingestion pipeline.

These are exposed automatically via /metrics by prometheus-fastapi-instrumentator
because they live in the default registry.
"""
from __future__ import annotations

from prometheus_client import Counter, Histogram

# ---------------------------------------------------------------- counters --
PIPELINE_FAILURES = Counter(
    "ldip_pipeline_failures_total",
    "Number of pipeline failures grouped by stage.",
    ["stage"],
)

CHUNKS_PRODUCED = Counter(
    "ldip_chunks_total",
    "Total number of chunks produced by the chunker.",
)

DOCUMENTS_INDEXED = Counter(
    "ldip_documents_indexed_total",
    "Total number of documents that reached the 'ready' state.",
)
CLASSIFICATION_LOW_CONFIDENCE = Counter(
    "ldip_document_classification_low_confidence_total",
    "Documents whose classifier result was below the configured confidence gate.",
)

# --------------------------------------------------------------- histograms --
OCR_DURATION = Histogram(
    "ldip_ocr_duration_seconds",
    "OCR stage duration in seconds.",
    buckets=(0.5, 1, 2, 5, 10, 30, 60, 120, 300, 600),
)

CHUNK_DURATION = Histogram(
    "ldip_chunk_duration_seconds",
    "Chunking stage duration in seconds.",
    buckets=(0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10, 30),
)

EMBEDDING_DURATION = Histogram(
    "ldip_embedding_duration_seconds",
    "Embedding stage duration in seconds.",
    buckets=(0.5, 1, 2, 5, 10, 30, 60, 120, 300),
)

INDEX_DURATION = Histogram(
    "ldip_index_duration_seconds",
    "FAISS indexing duration in seconds.",
    buckets=(0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10, 30, 60),
)

CHUNK_COUNT = Histogram(
    "ldip_chunk_count",
    "Number of chunks per document.",
    buckets=(1, 5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000),
)

# ---------------------------------------------------------- RAG / LLM ------
RETRIEVAL_LATENCY = Histogram(
    "ldip_rag_retrieval_latency_seconds",
    "Retrieval (embed + FAISS + RRF) latency in seconds.",
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5),
)

RERANK_LATENCY = Histogram(
    "ldip_rag_rerank_latency_seconds",
    "Cross-encoder rerank latency in seconds.",
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5),
)

LLM_TTFB = Histogram(
    "ldip_llm_time_to_first_byte_seconds",
    "Time from request start to first streamed token.",
    buckets=(0.1, 0.25, 0.5, 1, 2, 4, 8, 16),
)

LLM_TOKENS_IN = Counter(
    "ldip_llm_tokens_in_total", "Total prompt tokens sent to the LLM."
)
LLM_TOKENS_OUT = Counter(
    "ldip_llm_tokens_out_total", "Total tokens generated by the LLM."
)
RAG_NO_CONTEXT = Counter(
    "ldip_rag_no_context_total",
    "Number of RAG calls that returned no usable context.",
)
